### PR TITLE
Nicole gui2

### PR DESCRIPTION
**Pull request by ndahlquist-cc**
game views complete

### CODE REVIEW

**Comment by ndahlquist-cc** [comment]
friendship views complete (missing something from orders to add to wishlist?)

**Comment by pjthomso** [comment]
+1

**Comment by BlackthornYugen** [comment]
+1

**Comment by BlackthornYugen** [comment]
We might want to remove the changes that aren't really changes. Probably line endings again. Check out the files under /migrations/

**Pull request merged**
