### PR TITLE
Added autonumber migration

### PR DESCRIPTION
**Pull request by BlackthornYugen**

### CODE REVIEW

**Comment by BlackthornYugen** [comment]
@SeaSharpe/everyone Could one or two people make sure this builds okay on their machine? Just need to checkout the branch and run the following in the nuget console:

```
Update-Database -TargetMigration:0 -Force
Update-Database
```

This will erase and rebuild all test data. Once rebuilt the IDs should all start at the correct numbers.

**Comment by naaturaz** [comment]
+1

**Comment by BlackthornYugen** [comment]
Appears to be working locally, would like one or two people to verify that it works before we merge this. 

Steps to test: 

```
NugetConsole: Update-Database -TargetMigration:0
<SWITCH TO SQL_AUTONUMBERS BRANCH>
NugetConsole: Update-Database
```

Check that there is data inside Games, Users, Members GameCategory tables. None of the autonumber ids should start at 1. Here's what I see in GameCategory: 

image

Before leaving the branch, to avoid bugs, revert the database again from nuget package console

```
NugetConsole: Update-Database -TargetMigration:0
<SWITCH TO ANY BRANCH>
NugetConsole: Update-Database
```

**Comment by dHofstede** [comment]
+1

**Comment by pjthomso** [comment]
+1

**Pull request merged**
