### PR TITLE
Nicole gui2

### PR DESCRIPTION
**Pull request by ndahlquist-cc**
check /Game/SearchGames to view the page GUI (form elements are not changed yet)
Once approved I'll finish applying to other views

### CODE REVIEW

**Comment by BlackthornYugen** [comment]
+1

**Comment by pjthomso** [comment]
A few things didn't work well on my wide screen monitor, also some of the css was in the bootstrap files and is being moved to main.css. Going over these with Nicole now.

**Comment by ndahlquist-cc** [comment]
changes moved from bootstrap.css to main.css.  Should be up to date now

**Comment by pjthomso** [comment]
Tested the bootstrap/main css changes and they are working now, despite the sidebar being only in one view I don't see any reason not to pull these changes now so +1

**Pull request merged**
